-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Хост: localhost
-- Время создания: Июл 08 2026 г., 11:14
-- Версия сервера: 8.4.8-8-beget-1-2
-- Версия PHP: 8.3.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `human2xn_jou`
--

-- --------------------------------------------------------

--
-- Структура таблицы `article_authors`
--
-- Создание: Май 05 2026 г., 12:09
-- Последнее обновление: Июл 07 2026 г., 13:34
--

DROP TABLE IF EXISTS `article_authors`;
CREATE TABLE `article_authors` (
  `id` bigint UNSIGNED NOT NULL,
  `article_id` bigint UNSIGNED NOT NULL,
  `author_num` int UNSIGNED NOT NULL COMMENT 'Порядковый номер автора',
  `author_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ID автора в eLibrary',
  `role` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '0-редактор, 23-рецензент и т.д.',
  `is_correspondent` tinyint(1) NOT NULL DEFAULT '0',
  `researcherid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `spin` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopusid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `orcid` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `surname_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `surname_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `surname_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patronymic_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patronymic_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patronymic_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `initials_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `initials_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `initials_cv` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Инициалы (чуваш)',
  `address_ru` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `address_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `address_cv` text COLLATE utf8mb4_unicode_ci,
  `town_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `town_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `town_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Город (чуваш)',
  `country_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Страна (чуваш)',
  `position_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `position_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `position_cv` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `degree` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `degree_ru` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `degree_en` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `degree_cv` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rank` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rank_ru` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rank_en` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rank_cv` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `other_info_ru` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `other_info_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `other_info_cv` text COLLATE utf8mb4_unicode_ci,
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Текст рецензии',
  `comment_date` date DEFAULT NULL,
  `org_name_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `org_name_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `org_name_cv` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Организация (чуваш)',
  `org_not_authentic` tinyint(1) NOT NULL DEFAULT '0',
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_not_authentic` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `article_authors`
--

INSERT INTO `article_authors` (`id`, `article_id`, `author_num`, `author_id`, `role`, `is_correspondent`, `researcherid`, `spin`, `scopusid`, `orcid`, `surname_ru`, `surname_en`, `surname_cv`, `name_ru`, `name_en`, `name_cv`, `patronymic_ru`, `patronymic_en`, `patronymic_cv`, `initials_ru`, `initials_en`, `initials_cv`, `address_ru`, `address_en`, `address_cv`, `town_ru`, `town_en`, `town_cv`, `country_ru`, `country_en`, `country_cv`, `position_ru`, `position_en`, `position_cv`, `degree`, `degree_ru`, `degree_en`, `degree_cv`, `rank`, `rank_ru`, `rank_en`, `rank_cv`, `other_info_ru`, `other_info_en`, `other_info_cv`, `comment`, `comment_date`, `org_name_ru`, `org_name_en`, `org_name_cv`, `org_not_authentic`, `email`, `email_not_authentic`, `created_at`, `updated_at`) VALUES
(51, 20, 1, NULL, NULL, 0, NULL, '4087-0713', NULL, '0009-0001-5728-9955', 'Гусаров', 'Gusarov', 'Гусаров', 'Юрий', 'Yuri', 'Юрий', 'Владимирович', 'Vladimirovich', 'Владимирович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-04 10:40:42', '2026-05-04 10:40:42'),
(62, 22, 1, NULL, NULL, 0, NULL, '2201-9555', NULL, '0000-0002-8798-8132', 'Леонтьев', 'Leontiev', 'Леонтьев', 'Алексей', 'Alexey', 'Алексей', 'Петрович', 'Петрович', 'Петрович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-04 11:07:26', '2026-05-04 11:07:26'),
(68, 24, 1, NULL, NULL, 0, NULL, '9427-2916', NULL, '0009-0005-9824-8008', 'Охотникова', 'Okhotnikova', 'Охотникова', 'Светлана', 'Svetlana', 'Светлана', 'Валерьевна', 'Valer\'evna', 'Валерьевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-04 11:32:29', '2026-05-04 11:32:29'),
(85, 29, 1, NULL, NULL, 0, NULL, '4009-6182', NULL, '0000-0002-0160-5162', 'Чибис', 'Chibis', 'Чибис', 'Александр', 'Alexander', 'Александр', 'Алексеевич', 'Alekseevich', 'Алексеевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 04:03:09', '2026-05-05 04:03:09'),
(104, 34, 1, NULL, NULL, 0, NULL, '1321-8267', NULL, '0000-0002-1132-7055', 'Бушуева', 'Bushueva', 'Бушуева', 'Любовь', 'Lyubov', 'Любовь', 'Ивановна', 'Ivanovna', 'Ивановна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, 'кандидат искусствоведения', 'кандидат искусствоведения', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 06:15:26', '2026-05-05 06:15:26'),
(114, 32, 1, NULL, NULL, 0, NULL, '7292-3285', NULL, '0000-0002-8798-8132', 'Студенцов', 'Studentsov', 'Студенцов', 'Олег', 'Oleg', 'Олег', 'Ростиславович', 'Rostislavovich', 'Ростиславович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 08:07:17', '2026-05-05 08:07:17'),
(123, 43, 1, NULL, NULL, 0, NULL, '3601-9440', NULL, '0000-0001-6031-2725', 'Гаврилов', 'Gavrilov', 'Гаврилов', 'Артем', 'Artem', 'Артем', 'Дмитриевич', 'Dmitrievich', 'Дмитриевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 08:54:23', '2026-05-05 08:54:23'),
(124, 42, 1, NULL, NULL, 0, NULL, '5576-1718', NULL, '0009-0006-8445-7877', 'Долгова', 'Dolgova', 'Долгова', 'Алевтина', 'Alevtina', 'Алевтина', 'Петровна', 'Petrovna', 'Петровна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 08:55:25', '2026-05-05 08:55:25'),
(125, 42, 2, NULL, NULL, 0, NULL, '7307-3164', NULL, '0000-0001-8664-3004', 'Петров', 'Petrov', 'Петров', 'Игорь', 'Igor', 'Игорь', 'Георгиевич', 'Georgievich', 'Георгиевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Уфа', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт этнологических исследований им. Р. Г. Кузеева УФИЦ РАН', 'Institute of Ethnological Research named after R. G. Kuzeev, Ufa Federal Research Center of the Russian Academy of Sciences', NULL, 0, NULL, 0, '2026-05-05 08:55:25', '2026-05-05 08:55:25'),
(126, 42, 3, NULL, NULL, 0, NULL, '3568-9832', NULL, '0000-0002-2784-8090', 'Ягафова', 'Yagafova', 'Ягафова', 'Екатерина', 'Ekaterina', 'Екатерина', 'Андреевна', 'Andreevna', 'Андреевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Самара', NULL, NULL, 'Россия', NULL, NULL, 'заведующий кафедрой философии, истории и теории мировой культуры', NULL, NULL, 'доктор исторических наук', 'доктор исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Самарский государственный социально-педагогический университет', 'Samara State Socio-Pedagogical University', NULL, 0, NULL, 0, '2026-05-05 08:55:25', '2026-05-05 08:55:25'),
(134, 26, 1, NULL, NULL, 0, NULL, '9584-8644', NULL, '0009-0007-6608-2829', 'Краснов', 'Krasnov', 'Краснов', 'Петр', 'Petr', 'Петр', 'Степанович', 'Stepanovich', 'Степанович', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат философских наук', 'кандидат философских наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'krasnov17@mail.ru', 0, '2026-05-05 09:07:40', '2026-05-05 09:07:40'),
(135, 27, 1, NULL, NULL, 0, NULL, '9793-2731', NULL, '0000-0002-2655-4779', 'Кропачев', 'Kropachev', 'Кропачев', 'Сергей', 'Sergej', 'Сергей', 'Александрович', 'Aleksandrovich', 'Александрович', NULL, NULL, NULL, NULL, NULL, NULL, 'Москва', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'доктор исторических наук', 'доктор исторических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт российской истории РАН', 'The Institute of Russian History of the Russian Academy of Sciences', NULL, 0, 'rektor@eipk.info', 0, '2026-05-05 09:10:33', '2026-05-05 09:10:33'),
(136, 28, 1, NULL, NULL, 0, NULL, '9209-6775', NULL, '0009-0005-4564-0903', 'Сараев', 'Saraev', 'Сараев', 'Андрей', 'Andrej', 'Андрей', 'Сергеевич', 'Sergeevich', 'Сергеевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'andrejsaraev@yandex.ru', 0, '2026-05-05 09:13:54', '2026-05-05 09:13:54'),
(137, 31, 1, NULL, NULL, 0, NULL, '8223-0279', NULL, '0000-0001-7730-2769', 'Серазетдинов', 'Serazetdinov', 'Серазетдинов', 'Борис', 'Boris', 'Борис', 'Уразбекович', 'Urazbekovich', 'Уразбекович', NULL, NULL, NULL, NULL, NULL, NULL, 'Москва', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт российской истории РАН', 'The Institute of Russian History of the Russian Academy of Sciences', NULL, 0, 'sbu54@bk.ru', 0, '2026-05-05 09:14:59', '2026-05-05 09:14:59'),
(138, 33, 1, NULL, NULL, 0, NULL, '4695-9894', NULL, '0009-0007-5483-3840', 'Смирнова', 'Smirnova', 'Смирнова', 'Наталья', 'Nаtalia', 'Наталья', 'Борисовна', 'Borisovna', 'Борисовна', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'da777L@yandex.ru', 0, '2026-05-05 09:15:48', '2026-05-05 09:15:48'),
(139, 35, 1, NULL, NULL, 0, NULL, '3001-3610', NULL, '0000-0002-2595-8974', 'Шайдуллин', 'SHajdullin', 'Шайдуллин', 'Рафаиль', 'Rafail', 'Рафаиль', 'Валеевич', 'Valeevich', 'Валеевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Казань', NULL, NULL, 'Россия', NULL, NULL, 'заведующий центром энциклопедистики', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт татарской энциклопедии и регионоведения им. М. Хасанова АН РТ', 'The Institute of Tatar Encyclopedia and Regional Studies named after M. Khasanov, Academy of Sciences of the Republic of Tatarstan', NULL, 0, 'srv60@yandex.ru', 0, '2026-05-05 09:16:12', '2026-05-05 09:16:12'),
(140, 37, 1, NULL, NULL, 0, NULL, '7855-6761', NULL, '0000-0003-0175-5678', 'Никифорова', 'Nikiforova', 'Никифорова', 'Вера', 'Vera', 'Вера', 'Витальевна', 'Vital\'evna', 'Витальевна', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'vera.nickiforova@yandex.ru', 0, '2026-05-05 09:16:35', '2026-05-05 09:16:35'),
(142, 39, 1, NULL, NULL, 0, NULL, '9632-0239', NULL, '0000-0003-0394-3170', 'Кондратьев', 'Kondratiev', 'Кондратьев', 'Михаил', 'Mikhail', 'Михаил', 'Григорьевич', 'Grigorievich', 'Григорьевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'Mikh-kondratev@yandex.ru', 0, '2026-05-05 09:27:57', '2026-05-05 09:27:57'),
(143, 40, 1, NULL, NULL, 0, NULL, '5560-2942', NULL, '0009-0004-4824-9443', 'Малинина', 'Malinina', 'Малинина', 'Алина', 'Alina', 'Алина', 'Александровна', 'Aleksandrovna', 'Александровна', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'младший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'm-anila@mail.ru', 0, '2026-05-05 09:28:33', '2026-05-05 09:28:33'),
(144, 44, 1, NULL, NULL, 0, NULL, '6519-8631', NULL, '0000-0001-9202-615X', 'Бойко', 'Boiko', 'Бойко', 'Иван', 'Ivan', 'Иван', 'Иванович', 'Ivanovich', 'Иванович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник', NULL, NULL, 'доктор исторических наук', 'доктор исторических наук', NULL, NULL, 'профессор', 'профессор', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 09:31:14', '2026-05-05 09:31:14'),
(145, 44, 2, NULL, NULL, 0, NULL, '1853-4274', NULL, '0000-0003-0764-5891', 'Казаков', 'Kazakov', 'Казаков', 'Николай', 'Nikolay', 'Николай', 'Александрович', 'Aleksandrovich', 'Александрович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'заведующий кафедрой социально-экономической географии и туризма', NULL, NULL, 'кандидат географических наук', 'кандидат географических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный университет им. И. Н. Ульянова', 'Chuvash State University named after I. N. Ulyanov', NULL, 0, NULL, 0, '2026-05-05 09:31:14', '2026-05-05 09:31:14'),
(146, 44, 3, NULL, NULL, 0, NULL, '7931-3809', NULL, '0000-0001-5791-6210', 'Минеев', 'Mineev', 'Минеев', 'Алексей', 'Alexey', 'Алексей', 'Игоревич', 'Igorevich', 'Игоревич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'заведующий межфакультетской базовой лабораторией 1 С', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный университет им. И. Н. Ульянова', 'Чувашский государственный университет им. И. Н. Ульянова', NULL, 0, NULL, 0, '2026-05-05 09:31:14', '2026-05-05 09:31:14'),
(147, 45, 1, NULL, NULL, 0, NULL, '3504-0279', NULL, '0000-0002-4557-8995', 'Мясников', 'Myasnikov', 'Мясников', 'Николай', 'Nikolay', 'Николай', 'Станиславович', 'Stanislavovich', 'Станиславович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'myasnikovn1988@gmail.com', 0, '2026-05-05 09:32:57', '2026-05-05 09:32:57'),
(148, 45, 2, NULL, NULL, 0, NULL, '2356-2300', NULL, '0000-0002-7865-5715', 'Михайлов', 'Mikhailov', 'Михайлов', 'Евгений', 'Evgeny', 'Евгений', 'Петрович', 'Petrovich', 'Петрович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 09:32:57', '2026-05-05 09:32:57'),
(149, 36, 1, NULL, NULL, 0, NULL, '7394-5255', NULL, '0000-0003-1564-8902', 'Виноградов', 'Vinogradov', 'Виноградов', 'Юрий', 'Yurij', 'Юрий', 'Михайлович', 'Mihajlovich', 'Михайлович', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник Центра регионального развития', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский республиканский институт образования', 'Chuvash Republican Institute of Education', NULL, 0, 'jurijvin46@mail.ru', 0, '2026-05-05 09:46:18', '2026-05-05 09:46:18'),
(150, 46, 1, NULL, NULL, 0, NULL, '6991-2246', NULL, '0000-0002-1072-9933', 'Салмин', 'Salmin', 'Салмин', 'Антон', 'Anton', 'Антон', 'Кириллович', 'Kirillovich', 'Кириллович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Санкт-Петербург', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'доктор исторических наук', 'доктор исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Музей антропологии и этнографии им. Петра Великого (Кунсткамера) РАН', 'Museum of Anthropology and Ethnography named after Peter the Great (Kunstkamera) of the Russian Academy of Sciences', NULL, 0, 'antsalmin@mail.ru', 0, '2026-05-05 09:46:48', '2026-05-05 09:46:48'),
(151, 41, 1, NULL, NULL, 0, NULL, '7394-5255', NULL, '0000-0003-1564-8902', 'Виноградов', 'Vinogradov', 'Виноградов', 'Юрий', 'Yurij', 'Юрий', 'Михайлович', 'Mihajlovich', 'Михайлович', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский республиканский институт образования', 'Chuvash Republican Institute of Education', NULL, 0, 'jurijvin46@mail.ru', 0, '2026-05-05 09:47:07', '2026-05-05 09:47:07'),
(152, 38, 1, NULL, NULL, 0, NULL, '4820-2852', NULL, '0000-0001-7695-4968', 'Софронова', 'Sofronova', 'Софронова', 'Ирина', 'Irina', 'Ирина', 'Владимировна', 'Vladimirovna', 'Владимировна', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'доцент кафедры чувашской филологии и культуры; старший научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный университет им. И. Н. Ульянова; Чувашский государственный институт гуманитарных наук', 'I. N. Ulyanov Chuvash State University, Chuvash State Institute of Humanities', NULL, 0, 'muxtar2@yandex.ru', 0, '2026-05-05 09:48:58', '2026-05-05 09:48:58'),
(153, 47, 1, NULL, NULL, 0, NULL, '9632-0239', NULL, '0000-0003-0394-3170', 'Кондратьев', 'Kondratiev', 'Кондратьев', 'Михаил', 'Michael', 'Михаил', 'Григорьевич', 'Grigor\'evich', 'Григорьевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник', NULL, NULL, 'доктор искусствоведения', 'доктор искусствоведения', NULL, NULL, 'профессор', 'профессор', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 10:00:09', '2026-05-05 10:00:09'),
(154, 48, 1, NULL, NULL, 0, NULL, '5885-9591', NULL, '0000-0001-7101-5283', 'Лебедев', 'Lebedev', 'Лебедев', 'Эдуард', 'Edward', 'Эдуард', 'Евгеньевич', 'Evgen\'evich', 'Евгеньевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, 'кандидат филологических наук', 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-05 10:15:01', '2026-05-05 10:15:01'),
(155, 49, 1, NULL, NULL, 0, NULL, '7223-4500', NULL, '0009-0000-8383-7196', 'Антипина', 'Antipina', 'Антипина', 'Анна', 'Anna', 'Анна', 'Анатольевна', 'Anatol\'evna', 'Анатольевна', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'младший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'annaaleksandrova1792@yandex.ru', 0, '2026-05-05 10:24:47', '2026-05-05 10:24:47'),
(156, 50, 1, NULL, NULL, 0, NULL, '6778-3258', NULL, '0000-0002-1721-4705', 'Баранцева', 'Barantseva', 'Баранцева', 'Наталья', 'Natalia', 'Наталья', 'Анатольевна', 'Anatolievna', 'Анатольевна', NULL, NULL, NULL, NULL, NULL, NULL, 'Абакан', NULL, NULL, 'Россия', NULL, NULL, 'заведующий кафедрой истории', NULL, NULL, 'кандидат исторических наук', 'кандидат исторических наук', NULL, NULL, 'доцент', 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Хакасский государственный университет им. Н. Ф. Катанова', 'The Khakassian State University named after N. F. Katanov', NULL, 0, 'barantzeva@inbox.ru', 0, '2026-05-05 10:31:13', '2026-05-05 10:31:13'),
(157, 51, 1, NULL, NULL, 0, NULL, '6519-8631', NULL, '0000-0001-9202-615X', 'Бойко', 'Boyko', 'Бойко', 'Иван', 'Ivan', 'Иван', 'Иванович', 'Ivanovich', 'Иванович', NULL, NULL, NULL, NULL, NULL, NULL, 'Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник', NULL, NULL, 'доктор исторических наук', 'доктор исторических наук', NULL, NULL, 'профессор', 'профессор', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'boyko2003@yandex.ru', 0, '2026-05-05 10:38:02', '2026-05-05 10:38:02'),
(158, 52, 1, NULL, NULL, 0, NULL, '1404-6354', NULL, '0000-0003-2491-4141', 'Воронцов', 'Vorontsov', 'Воронцов', 'Владимир', 'Vladimir', 'Владимир', 'Степанович', 'Stepanovich', 'Степанович', NULL, NULL, NULL, NULL, NULL, NULL, 'Екатеринбург', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, 'кандидат исторических наук', NULL, NULL, NULL, 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт философии и права Уральского отделения РАН', 'The Institute of Philosophy and Law, the Ural Branch of the Russian Academy of Sciences', NULL, 0, 'vvorontsov@rambler.ru', 0, '2026-05-05 10:55:08', '2026-05-05 10:55:08'),
(159, 53, 1, NULL, NULL, 0, NULL, '2525-4050', NULL, '0000-0003-3051-3184', 'Дегтярева', 'Degtyareva', 'Дегтярева', 'Наталья', 'Natalya', 'Наталья', 'Александровна', 'Aleksandrovna', 'Александровна', NULL, NULL, NULL, NULL, NULL, NULL, 'Оренбург', NULL, NULL, 'Россия', NULL, NULL, 'доцент кафедры истории', NULL, NULL, 'кандидат исторических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Оренбургский государственный университет', 'Orenburg State University', NULL, 0, 'degtjareva-natasha@mail.ru', 0, '2026-05-05 11:04:03', '2026-05-05 11:04:03'),
(160, 54, 1, NULL, NULL, 0, NULL, NULL, NULL, '0000-0001-7620-7794', 'Пичугин', 'Pichugin', 'Пичугин', 'Аркадий', 'Arkady', 'Аркадий', 'Юрьевич', 'Yur\'evich', 'Юрьевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Казань', NULL, NULL, 'Россия', NULL, NULL, 'доцент кафедры тактики, подполковник', NULL, NULL, 'кандидат исторических наук', NULL, NULL, NULL, 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Казанское высшее танковое командное училище', 'Kazan Higher Tank Command School', NULL, 0, 'arcad1977@yandex.ru', 0, '2026-05-05 11:11:43', '2026-05-05 11:11:43'),
(161, 21, 1, NULL, NULL, 0, NULL, '4379-8527', NULL, '0000-0003-3982-6013', 'Завьялов', 'Zavyalov', 'Завьялов', 'Аркадий', 'Arkady', 'Аркадий', 'Иванович', 'Ivanovich', 'Иванович', NULL, NULL, NULL, NULL, NULL, NULL, 'Москва', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Национальный научно-исследовательский институт общественного здоровья им. Н.А. Семашко', 'N. A. Semashko National Research Institute of Public Health', NULL, 0, 'ark.zavyalow@yandex.ru', 0, '2026-05-05 11:18:05', '2026-05-05 11:18:05'),
(162, 21, 2, NULL, NULL, 0, NULL, '4729-5379', NULL, '0000-0002-8695-829X', 'Якупов', 'Yakupov', 'Якупов', 'Ильяс', 'Ilyas', 'Ильяс', 'Абдуллович', 'Abdullovich', 'Абдуллович', NULL, NULL, NULL, NULL, NULL, NULL, 'Москва', NULL, NULL, 'Россия', NULL, NULL, 'заведующий филиалом «Зеленоградский»', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Московский научно-практический Центр дерматовенерологии и косметологии', 'Moscow Scientifi c and Practical Center of Dermatovenereology and Cosmetology', NULL, 0, 'yailyas@mail.ru', 0, '2026-05-05 11:18:05', '2026-05-05 11:18:05'),
(163, 23, 1, NULL, NULL, 0, NULL, '6547-1027', NULL, '0000-0003-3819-3103', 'Кирчанов', 'Kirchanov', 'Кирчанов', 'Максим', 'Maksim', 'Максим', 'Валерьевич', 'Valer\'evich', 'Валерьевич', NULL, NULL, NULL, NULL, NULL, NULL, 'Воронеж', NULL, NULL, 'Россия', NULL, NULL, 'доцент', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Воронежский государственный университет', 'Voronezh State University', NULL, 0, 'maksym_kyrchanoff@hotmail.com', 0, '2026-05-05 11:24:03', '2026-05-05 11:24:03'),
(164, 25, 1, NULL, NULL, 0, NULL, '9663-6484', NULL, '0000-0002-4769-7744', 'Королева', 'Koroleva', 'Королева', 'Татьяна', 'Tat\'yana', 'Татьяна', 'Валерьевна', 'Valer\'evna', 'Валерьевна', NULL, NULL, NULL, NULL, NULL, NULL, 'Иваново', NULL, NULL, 'Россия', NULL, NULL, 'доцент кафедры истории, философии и права', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ивановский государственный энергетический университет им. В. И. Ленина', 'Ivanovo State Power Engineering University named after V. I. Lenin', NULL, 0, 'kor_tv@mail.ru', 0, '2026-05-05 11:29:15', '2026-05-05 11:29:15'),
(165, 25, 2, NULL, NULL, 0, NULL, '5923-1682', NULL, '0000-0003-2191-1965', 'Котлова', 'Kotlova', 'Котлова', 'Татьяна', 'Tat\'yana', 'Татьяна', 'Борисовна', 'Borisovna', 'Борисовна', NULL, NULL, NULL, NULL, NULL, NULL, 'Иваново', NULL, NULL, 'Россия', NULL, NULL, 'проректор по молодежной политике', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ивановский государственный энергетический университет им. В. И. Ленина', 'Ivanovo State Power Engineering University named after V. I. Lenin', NULL, 0, 'ktb@ispu.ru', 0, '2026-05-05 11:29:15', '2026-05-05 11:29:15'),
(166, 25, 3, NULL, NULL, 0, NULL, '4818-1147', NULL, '0000-0003-2338-5276', 'Будник', 'Budnik', 'Будник', 'Галина', 'Galina', 'Галина', 'Анатольевна', 'Anatol\'evna', 'Анатольевна', NULL, NULL, NULL, NULL, NULL, NULL, 'Иваново', NULL, NULL, 'Россия', NULL, NULL, 'профессор кафедры истории, философии и права', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ивановский государственный энергетический университет им. В. И. Ленина', 'Ivanovo State Power Engineering University named after V. I. Lenin', NULL, 0, 'budn@inbox.ru', 0, '2026-05-05 11:29:15', '2026-05-05 11:29:15'),
(168, 56, 1, NULL, NULL, 0, NULL, '9199-8740', NULL, '0009-0005-2667-5131', 'Коршунова', 'Korshunova', 'Коршунова', 'Кристина', 'Kristina', 'Кристина', 'Николаевна', 'Nikolaevna', 'Николаевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Москва', NULL, NULL, 'Россия', NULL, NULL, 'специалист по учебно-методической работе', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Российский государственный гуманитарный университет', 'Russian State University for the Humanities', NULL, 0, NULL, 0, '2026-05-06 05:26:28', '2026-05-06 05:26:28'),
(169, 55, 1, NULL, NULL, 0, NULL, '4087-0713', NULL, '0009-0001-5728-9955', 'Гусаров', 'Gusarov', 'Гусаров', 'Юрий', 'Yuri', 'Юрий', 'Владимирович', 'Владимирович', 'Владимирович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 05:28:41', '2026-05-06 05:28:41'),
(170, 18, 1, NULL, NULL, 0, NULL, '2167-9126', NULL, '0000-0002-6354-4676', 'Исаев', 'Isaev', 'Исаев', 'Юрий', 'Yuri', 'Юрий', 'Николаевич', 'Nikolaevich', 'Николаевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'директор, главный редактор научного журнала', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 05:33:12', '2026-05-06 05:33:12'),
(171, 19, 1, NULL, NULL, 0, NULL, '9745-7723', NULL, '0009-0004-3057-2525', 'Андреев', 'Andreev', 'Андреев', 'Олег', 'Oleg', 'Олег', 'Васильевич', 'Vasil\'evich', 'Васильевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'доцент кафедры отечественной истории им. А. В. Арсентьевой', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный университет им. И. Н. Ульянова', 'I. N. Ulyanov Chuvash State University', NULL, 0, NULL, 0, '2026-05-06 05:36:20', '2026-05-06 05:36:20'),
(173, 57, 1, NULL, NULL, 0, NULL, '4695-9894', NULL, '0009-0007-5483-3840', 'Смирнова', 'Smirnova', 'Смирнова', 'Наталья', 'Nаtalia', 'Наталья', 'Борисовна', 'Borisovna', 'Борисовна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 06:13:25', '2026-05-06 06:13:25'),
(174, 58, 1, NULL, NULL, 0, NULL, '3472-2623', NULL, '0009-0007-2096-6514', 'Сергеева', 'Sergeeva', 'Сергеева', 'Евгения', 'Evgeniya', 'Евгения', 'Валерьевна', 'Valeryevna', 'Валерьевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'evgenjaserg@yandex.ru', 0, '2026-05-06 06:25:13', '2026-05-06 06:25:13'),
(175, 59, 1, NULL, NULL, 0, NULL, '7345-6118', NULL, '0000-0002-7930-9072', 'Харитонова', 'Kharitonova', 'Харитонова', 'Валентина', 'Valentina', 'Валентина', 'Григорьевна', 'Grigorievna', 'Григорьевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 08:28:42', '2026-05-06 08:28:42'),
(176, 60, 1, NULL, NULL, 0, NULL, '3568-9832', NULL, '0000-0002-2784-8090', 'Ягафова', 'Yagafova', 'Ягафова', 'Екатерина', 'Ekaterina', 'Екатерина', 'Андреевна', 'Andreevna', 'Андреевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Самара', NULL, NULL, 'Россия', NULL, NULL, 'заведующий кафедрой философии, истории и теории мировой культуры и искусства', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Самарский государственный социально-педагогический университет', 'Самар патшалăх социо-педагогика университечĕн', NULL, 0, 'yagafova@yandex.ru', 0, '2026-05-06 08:39:07', '2026-05-06 08:39:07'),
(177, 61, 1, NULL, NULL, 0, NULL, '9055-6207', NULL, '0000-0002-8798-8132', 'Леонтьев', 'Leontiev', 'Леонтьев', 'Денис', 'Denis', 'Денис', 'Михайлович', 'Mikhailovich', 'Михайлович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'младший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 08:47:18', '2026-05-06 08:47:18'),
(178, 62, 1, NULL, NULL, 0, NULL, '3339-4520', NULL, '0000-0001-8560-9146', 'Мышкина', 'Myshkina', 'Мышкина', 'Альбина', 'Albina', 'Альбина', 'Федоровна', 'Fedorovna', 'Федоровна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 08:55:52', '2026-05-06 08:55:52'),
(179, 63, 1, NULL, NULL, 0, NULL, '1321-8267', NULL, '0000-0002-1132-7055', 'Бушуева', 'Bushueva', 'Бушуева', 'Любовь', 'Lyubov', 'Любовь', 'Ивановна', 'Ivanovna', 'Ивановна', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 09:13:18', '2026-05-06 09:13:18'),
(180, 64, 1, NULL, NULL, 0, NULL, '7394-5255', NULL, '0000-0003-1564-8902', 'Виноградов', 'Vinogradov', 'Виноградов', 'Юрий', 'Yuriy', 'Юрий', 'Михайлович', 'Mihajlovich', 'Михайлович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник Центра регионального развития', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский республиканский институт образования', 'Чӑваш Республикин вӗренӳ институчӗ', NULL, 0, NULL, 0, '2026-05-06 09:15:40', '2026-05-06 09:15:40'),
(181, 65, 1, NULL, NULL, 0, NULL, '5885-9591', NULL, '0000-0001-7101-5283', 'Лебедев', 'Lebedev', 'Лебедев', 'Эдуард', 'Eduard', 'Эдуард', 'Евгеньевич', 'Evgen\'evich', 'Евгеньевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 09:29:42', '2026-05-06 09:29:42'),
(182, 66, 1, NULL, NULL, 0, NULL, '3339-4520', NULL, '0000-0001-8560-9146', 'Мышкина', 'Myshkina', 'Мышкина', 'Альбина', 'Albina', 'Альбина', 'Федоровна', 'Fedorovna', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 10:01:22', '2026-05-06 10:01:22'),
(183, 67, 1, NULL, NULL, 0, NULL, '7855-6761', NULL, '0000-0003-0175-5678', 'Никифорова', 'Nikiforova', 'Никифорова', 'Вера', 'Vera', 'Вера', 'Витальевна', 'Vital\'evna', 'Витальевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 10:10:13', '2026-05-06 10:10:13'),
(184, 68, 1, NULL, NULL, 0, NULL, '5453-6471', NULL, '0009-0005-7822-5204', 'Мордвинова', 'Mordvinova', 'Мордвинова', 'Антонина', 'Antonina', 'Антонина', 'Ильинична', 'Ilyinichna', 'Ильинична', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, NULL, NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', NULL, NULL, 0, 'amordvinova@yandex.ru', 0, '2026-05-06 10:21:12', '2026-05-06 10:21:12'),
(185, 69, 1, NULL, NULL, 0, NULL, '1321-8267', NULL, '0000-0002-1132-7055', 'Бушуева', 'Bushuyeva', 'Бушуева', 'Любовь', 'Lyubov', 'Любовь', 'Ивановна', 'Ivanovna', 'Ивановна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 10:22:25', '2026-05-06 10:22:25'),
(186, 70, 1, NULL, NULL, 0, NULL, '6751-6833', NULL, '0000-0001-6058-9652', 'Касимов', 'Kasimov', 'Касимов', 'Евгений', 'Evgeny', 'Евгений', 'Витальевич', 'Vitalievich', 'Витальевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'Доцент кафедры отечественной и всеобщей истории', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный педагогический университет им. И.Я. Яковлева', 'Chuvash State Pedagogical University named after I. Y. Yakovlev', NULL, 0, 'kasimov-chgpu@mail.ru', 0, '2026-05-06 10:32:22', '2026-05-06 10:32:22'),
(188, 72, 1, NULL, NULL, 0, NULL, '7245-7974', NULL, '0009-0007-9086-8186', 'Зарубин', 'Zarubin', 'Зарубин', 'Андрей', 'Andrey', 'Андрей', 'Николаевич', 'Nikolaevich', 'Николаевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-06 10:44:47', '2026-05-06 10:44:47'),
(190, 71, 1, NULL, NULL, 0, NULL, '3601-9440', NULL, '0000- 0001-6031-272', 'Гаврилов', 'Gavrilov', 'Гаврилов', 'Артем', 'Artem', 'Артем', 'Дмитриевич', 'Dmitrievich', 'Дмитриевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, 'artmaster28@rambler.ru', 0, '2026-05-06 10:55:30', '2026-05-06 10:55:30'),
(191, 74, 1, NULL, NULL, 0, NULL, '1406-7364', NULL, '0000-0002-6077-7183', 'Дыбо', 'Dybo', 'Дыбо', 'Анна', 'Anna', 'Анна', 'Владимировна', 'Vladimirovna', 'Владимировна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Москва', NULL, NULL, 'Россия', NULL, NULL, 'заведующий Отделом урало-алтайских языков, член-корреспондент РАН', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт языкознания РАН', 'Institute of Linguistics of the Russian Academy of Sciences', NULL, 0, NULL, 0, '2026-05-06 11:04:56', '2026-05-06 11:04:56'),
(192, 75, 1, NULL, NULL, 0, NULL, '2094-2065', NULL, '0000-0002-1549-9639', 'Напольских', 'Napolskikh', 'Напольских', 'Владимир', 'Vladimir', 'Владимир', 'Владимирович', 'Vladimirovich', 'Владимирович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Екатеринбург', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник, руководитель Центра историко-лингвистических исследований, член-корреспондент РАН', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт истории и археологии УрО РАН', 'Institute of History and Archaeology of the Ural Branch of the Russian Academy of Sciences', NULL, 0, NULL, 0, '2026-05-06 11:23:33', '2026-05-06 11:23:33'),
(194, 76, 1, NULL, NULL, 0, NULL, '5576-1718', NULL, '0009-0006-8445-7877', 'Долгова', 'Dolgova', 'Долгова', 'Алевтина', 'Alevtina', 'Алевтина', 'Петровна', 'Petrovna', 'Петровна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 03:53:49', '2026-05-07 03:53:49'),
(195, 77, 1, NULL, NULL, 0, NULL, '5885-9591', NULL, '0000-0001-7101-5283', 'Лебедев', 'Lebedev', 'Лебедев', 'Эдуард', 'Eduard', 'Эдуард', 'Евгеньевич', 'Evgen\'evich', 'Евгеньевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 03:59:02', '2026-05-07 03:59:02'),
(196, 78, 1, NULL, NULL, 0, NULL, '1126-8628', NULL, '0009-0003-0699-435X', 'Михайлова', 'Mikhailova', 'Михайлова', 'Ольга', 'Olga', 'Ольга', 'Николаевна', 'Nikolaevna', 'Николаевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 04:16:10', '2026-05-07 04:16:10'),
(197, 79, 1, NULL, NULL, 0, NULL, '9246-0493', NULL, '0009-0003-4846-527X', 'Семенов', 'Semenov', 'Семенов', 'Евгений', 'Evgeniy', 'Евгений', 'Валериевич', 'Valerievich', 'Валериевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'младший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 04:21:01', '2026-05-07 04:21:01'),
(198, 30, 1, NULL, NULL, 0, NULL, NULL, NULL, '0000-0002-4644-2969', 'Зимони', 'Zimony', 'Зимони', 'Иштван', 'István', 'Иштван', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Сегед', NULL, NULL, 'Венгрия', NULL, NULL, 'профессор кафедры средневековой истории', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Сегедский университет', 'Szeged University', NULL, 0, NULL, 0, '2026-05-07 04:26:44', '2026-05-07 04:26:44'),
(199, 30, 2, NULL, '3', 0, NULL, NULL, NULL, NULL, 'Дмитриева', 'Dmitrieva', 'Дмитриева', 'Юдит', 'Judith', 'Юдит', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 04:26:44', '2026-05-07 04:26:44'),
(200, 80, 1, NULL, NULL, 0, NULL, '9209-6775', NULL, '0009-0005-4564-0903', 'Сараев', 'Saraev', 'Сараев', 'Андрей', 'Andrei', 'Андрей', 'Сергеевич', 'Sergeevich', 'Сергеевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 04:57:07', '2026-05-07 04:57:07'),
(201, 81, 1, NULL, NULL, 0, NULL, NULL, NULL, '0000-0001-5462-2954', 'Чаглайан', 'Caglayan', 'Чаглайан', 'Егяна', 'Yegana', 'Егяна', 'Хафизовна', 'Hafizovna', 'Хафизовна', NULL, NULL, NULL, NULL, NULL, NULL, 'Mu§', NULL, NULL, 'Turkiye', NULL, NULL, 'заведующий кафедрой истории средних веков', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'университет Муш Алп Арслан', 'Mu§ Alparslan University', NULL, 0, NULL, 0, '2026-05-07 05:06:16', '2026-05-07 05:06:16'),
(202, 82, 1, NULL, NULL, 0, NULL, NULL, NULL, '0000-0002-6449-5618', 'Адягаши', 'Agyagasi', 'Адягаши', 'Клара', 'Klara', 'Клара', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Дебрецен', NULL, NULL, 'Венгрия', NULL, NULL, 'профессор эмерит Института славистики', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Дебреценский университет', 'University of Debrecen', NULL, 0, NULL, 0, '2026-05-07 05:14:30', '2026-05-07 05:14:30'),
(203, 83, 1, NULL, NULL, 0, NULL, '6647-7296', NULL, '0000-0002-4659-273X', 'Еникеев', 'Enikeev', 'Еникеев', 'Ильдар', 'Ildar', 'Ильдар', 'Ахнафович', 'Ahnafovich', 'Ахнафович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Казань', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт языка, литературы и искусства им. Г. Ибрагимова АН РТ', 'G. Ibragimov Institute of Language, Literature and Art, Tatarstan Academy of Sciences', NULL, 0, NULL, 0, '2026-05-07 05:23:04', '2026-05-07 05:23:04'),
(204, 84, 1, NULL, NULL, 0, NULL, '3806-6010', NULL, '0000-0002-2626-6953', 'Саракуева', 'Sarakueva', 'Саракуева', 'Асият', 'Asiyat', 'Асият', 'Мазировна', 'Mazirovna', 'Мазировна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Нальчик', NULL, NULL, 'Россия', NULL, NULL, 'редактор-ведущий телепрограмм', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ГКУ «КБР-Медиа»', 'State-owned institution \"KBR-Media\"', NULL, 0, NULL, 0, '2026-05-07 05:53:20', '2026-05-07 05:53:20'),
(205, 85, 1, NULL, NULL, 0, NULL, '6295-7503', NULL, '0000-0002-6504-3410', 'Шеянова', 'Sheyanova', 'Шеянова', 'Светлана', 'Svetlana', 'Светлана', 'Васильевна', 'Vasil\'evna', 'Васильевна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Саранск', NULL, NULL, NULL, NULL, NULL, 'профессор кафедры мордовских языков и литературы', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Национальный исследовательский Мордовский государственный университет имени Н. П. Огарева', 'National Research Mordovian State University named after N. P. Ogarev', NULL, 0, NULL, 0, '2026-05-07 06:02:14', '2026-05-07 06:02:14'),
(206, 86, 1, NULL, '4', 0, NULL, '5885-9591', NULL, '0000-0001-7101-5283', 'Лебедев', 'Lebedev', 'Лебедев', 'Эдуард', 'Eduard', 'Эдуард', 'Евгеньевич', 'Evgen\'evich', 'Евгеньевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 06:11:45', '2026-05-07 06:11:45'),
(207, 86, 2, NULL, '4', 0, NULL, '2201-9555', NULL, '0000-0002-8798-8132', 'Леонтьев', 'Leontiev', 'Леонтьев', 'Алексей', 'Alexey', 'Алексей', 'Петрович', 'Петрович', 'Петрович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 06:11:45', '2026-05-07 06:11:45'),
(208, 87, 1, NULL, NULL, 0, NULL, '5453-6471', NULL, '0009-0005-7822-5204', 'Мордвинова', 'Mordvinova', 'Мордвинова', 'Антонина', 'Antonina', 'Антонина', 'Ильинична', 'Il\'inichna', 'Ильинична', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'ведущий научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 08:13:48', '2026-05-07 08:13:48'),
(210, 89, 1, NULL, NULL, 0, NULL, '7959-0809', NULL, '0000-0003-3574-327X', 'Берман', 'Berman', 'Берман', 'Андрей', 'Andrey', 'Андрей', 'Геннадьевич', 'Gennad\'evich', 'Геннадьевич', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'заведующий кафедрой отечественной и всеобщей истории', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный педагогический университет им. И. Я. Яковлева', 'Chuvash State Pedagogical University named after I. Y. Yakovlev', NULL, 0, NULL, 0, '2026-05-07 08:30:38', '2026-05-07 08:30:38'),
(211, 90, 1, NULL, NULL, 0, NULL, '7470-9153', NULL, '0000-0003-4200-2568', 'Садиков', 'Sadikov', 'Садиков', 'Ранус', 'Ranus', 'Ранус', 'Рафикович', 'Rafikovich', 'Рафикович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Уфа', NULL, NULL, 'Россия', NULL, NULL, 'главный научный сотрудник отдела этнографии', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Институт этнологических исследований им. Р. Г. Кузеева Уфимского федерального исследовательского центра РАН', 'Institute of Ethnological Research R. G. Kuzeev Ufa federal research center of the Russian Academy of Sciences', NULL, 0, NULL, 0, '2026-05-07 09:08:24', '2026-05-07 09:08:24'),
(212, 91, 1, NULL, NULL, 0, NULL, '2201-9555', NULL, '0000-0002-8798-8132', 'Леонтьев', 'Leontiev', 'Леонтьев', 'Алексей', 'Alexey', 'Алексей', 'Петрович', 'Petrovich', 'Петрович', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 09:15:54', '2026-05-07 09:15:54'),
(213, 88, 1, NULL, NULL, 0, NULL, NULL, NULL, '0009-00065576-1718-', 'Долгова', 'Dolgova', 'Долгова', 'Алевтина', 'Alevtina', 'Алевтина', 'Петровна', 'Petrovna', 'Петровна', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'старший научный сотрудник', NULL, NULL, NULL, 'кандидат филологических наук', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-05-07 09:39:38', '2026-05-07 09:39:38'),
(215, 73, 1, NULL, NULL, 0, NULL, '7245-7974', NULL, '0009-0007-9086-8186', 'Мордвинова', 'Mordvinova', 'Мордвинова', 'Антонина', 'Antonina', 'Антонина', 'Ильинична', 'Il\'inichna', 'Ильинична', NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', NULL, NULL, 'Россия', NULL, NULL, 'научный сотрудник', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-06-10 04:59:16', '2026-06-10 04:59:16');
INSERT INTO `article_authors` (`id`, `article_id`, `author_num`, `author_id`, `role`, `is_correspondent`, `researcherid`, `spin`, `scopusid`, `orcid`, `surname_ru`, `surname_en`, `surname_cv`, `name_ru`, `name_en`, `name_cv`, `patronymic_ru`, `patronymic_en`, `patronymic_cv`, `initials_ru`, `initials_en`, `initials_cv`, `address_ru`, `address_en`, `address_cv`, `town_ru`, `town_en`, `town_cv`, `country_ru`, `country_en`, `country_cv`, `position_ru`, `position_en`, `position_cv`, `degree`, `degree_ru`, `degree_en`, `degree_cv`, `rank`, `rank_ru`, `rank_en`, `rank_cv`, `other_info_ru`, `other_info_en`, `other_info_cv`, `comment`, `comment_date`, `org_name_ru`, `org_name_en`, `org_name_cv`, `org_not_authentic`, `email`, `email_not_authentic`, `created_at`, `updated_at`) VALUES
(218, 92, 1, NULL, NULL, 0, NULL, NULL, NULL, '0000-0002-4644-2969', 'Зимони', 'Zimoni', 'Зимони', 'И.', 'I.', 'И.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Сегед', 'Szeged', 'Сегед хули', 'Венгрия', 'Hungary', 'Венгри', 'профессор кафедры средневековой истории', 'Professor of the Department of Medieval History', 'вӑтам ӗмӗрсен историйӗн кафедрин профессорӗ', NULL, 'доктор исторических наук', 'Doctor of Historical Sciences', 'истори ӑслӑлӑхӗсен докторӗ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Сегедской университет', 'Szeged University', NULL, 0, NULL, 0, '2026-07-07 10:34:07', '2026-07-07 10:34:07'),
(219, 92, 2, NULL, '3', 0, NULL, NULL, NULL, NULL, 'Дмитриева', 'Dmitrieva', 'Дмитриева', 'Ю.', 'Yu.', 'Ю.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'г. Чебоксары', 'Cheboksary', 'Шупашкар хули', 'Россия', 'Russia', 'Раҫҫей', 'старший научный сотрудник', NULL, NULL, NULL, 'кандидат филологических наук', 'senior researcher', 'ӑслӑлӑх аслӑ ӗҫтешӗ', NULL, NULL, 'Candidate of Philological Sciences', 'филологи ӑслӑлӑхӗсен кандидачӗ', NULL, NULL, NULL, NULL, NULL, 'Чувашский государственный институт гуманитарных наук', 'Chuvash State Institute of Humanities', NULL, 0, NULL, 0, '2026-07-07 10:34:07', '2026-07-07 10:34:07');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `article_authors`
--
ALTER TABLE `article_authors`
  ADD PRIMARY KEY (`id`),
  ADD KEY `article_authors_article_id_author_num_index` (`article_id`,`author_num`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `article_authors`
--
ALTER TABLE `article_authors`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=220;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `article_authors`
--
ALTER TABLE `article_authors`
  ADD CONSTRAINT `article_authors_article_id_foreign` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
